// <auto-generated />
using System;
using Db_FrontDeskApp.DataConfig;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Db_FrontDeskApp.Migrations
{
    [DbContext(typeof(DbConfig))]
    [Migration("20230802092832_remainingCapacityAdded")]
    partial class remainingCapacityAdded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Db_FrontDeskApp.Model.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("FacilityId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Package")
                        .HasColumnType("int");

                    b.Property<DateTime>("RetrievedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("RetrievedPackage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StoredDate")
                        .HasColumnType("datetime2");

                    b.HasKey("CustomerId");

                    b.HasIndex("FacilityId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("Db_FrontDeskApp.Model.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<string>("FacilityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LargeCapacity")
                        .HasColumnType("int");

                    b.Property<int>("LargeRemainingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MediumRemainingCapacity")
                        .HasColumnType("int");

                    b.Property<int>("MeduimCapacity")
                        .HasColumnType("int");

                    b.Property<int>("SmallCapacity")
                        .HasColumnType("int");

                    b.Property<int>("SmallRemainingCapacity")
                        .HasColumnType("int");

                    b.HasKey("FacilityId");

                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("Db_FrontDeskApp.Model.Customer", b =>
                {
                    b.HasOne("Db_FrontDeskApp.Model.Facility", "FacilityLink")
                        .WithMany("CustomerList")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FacilityLink");
                });

            modelBuilder.Entity("Db_FrontDeskApp.Model.Facility", b =>
                {
                    b.Navigation("CustomerList");
                });
#pragma warning restore 612, 618
        }
    }
}
